
name: CI simple

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Étape de test (simulée)
        run: echo "Tests OK"

      - name: Étape de déploiement conditionnelle
        if: ${{ hashFiles('deploy.flag') != '' }}
        run: echo "Fichier deploy.flag détecté"